---
default_language_version:
  python: python3.12

repos:
  - repo: https://github.com/worgarside/pre-commit-hooks-dependency-sync
    rev: 1.3.1
    hooks:
      - id: sync-additional-dependencies

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.5
    hooks:
      - id: ruff-format
      - id: ruff

  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.7
    hooks:
      - id: actionlint

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        args:
          - --maxkb=1000
      - id: check-case-conflict
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: pretty-format-json
        args:
          - --no-sort-keys
          - --autofix
          - --indent
          - '2'
      - id: trailing-whitespace

  - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
    rev: 0.2.3
    hooks:
      - id: yamlfmt
        args:
          - --mapping
          - '2'
          - --sequence
          - '4'
          - --offset
          - '2'
          - --width
          - '4096'

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.37.1
    hooks:
      - id: yamllint
        args:
          - --format
          - parsable
          - --strict

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.0
    hooks:
      - id: mypy
        args:
          - --strict
          - --show-error-codes
        additional_dependencies:
          - gitpython==3.1.44
          - pydantic==2.10.6
          - pygithub==2.6.1
          - types-Pillow
          - types-requests
          - wg-utilities==5.17.4
          - git+https://github.com/AppDaemon/appdaemon.git

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-blanket-type-ignore
      - id: python-check-mock-methods

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        additional_dependencies:
          - tomli==2.2.1
