---
name: 'CI: Validation & Deployment'

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment to deploy to
        required: true
        default: development
        type: choice
        options:
          - development
          - production
  push:
    branches:
      - main

jobs:
  ci-validation:
    name: 'CI: Validation'
    uses: worgarside/github-config-files/.github/workflows/__ci_validation.yml@main
    with:
      build-branch: '${{ github.ref }}'
      build-type: 'python'
      python-version: '3.11'
      unit-test: ''
    secrets: inherit

  ci-deployment:
    name: 'CI: Deployment'
    needs: ci-validation
    permissions:
      id-token: write
    if: github.event_name == 'push' || inputs.environment == 'production'
    uses: worgarside/github-config-files/.github/workflows/__ci_deployment.yml@main
    with:
      build-branch: '${{ github.ref }}'
      build-type: 'python'
      event-name: '${{ github.event_name }}'
      node-build-directory: ''
      path-to-__version__-file: ''
      python-version: '3.11'
      unit-test: ''
      update-pyproject-toml: 'true'
      update-json-file-path: ''
      update-yaml-file-path: ''
      workflow-dispatch-env: '${{ inputs.environment }}'
    secrets: inherit
